### ISSUE TITLE
league_ranking.smx fail load

### ISSUE THREAD

**Issue by LemonPAKA** [csgo-league/csgo-league-game#1]
L 06/03/2019 - 13:13:07: SourceMod error session started
L 06/03/2019 - 13:13:07: Info (map "de_dust2") (file "errors_20190603.log")
L 06/03/2019 - 13:13:07: [SM] Unable to load plugin "league_ranking.smx": Could not find required plugin "LeagueRanking"

**Comment by B3none** [comment]
oof, i'll get this fixed for you. The plugins side of this is still in a very unstable state at the moment

**Comment by B3none** [comment]
Fixed, try the latest version.

**Comment by LemonPAKA** [comment]
dont know why it still the same....I used the lastest inc and sp file

**Comment by WardPearce** [comment]
Damn, that's hard to fuck up considering he just ripped the code from RankeME.

**Comment by B3none** [comment]
Use the latest release. Tested and working.
